- url: https://www.youtube.com/watch?v=yrtXM2zzKo4
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=oqOPsX-A57Q
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=jbC-PXlBzjE
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=hZxiKDpribo
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=hZxiKDpribo
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=hZxiKDpribo
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=W03v-lUH8qQ
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=FBAaxCG00SE
  album_name: ''
  collection_name: Omegle Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=81sr-Cn1IeE
  album_name: ''
  collection_name: Omegle Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=STQ1U7ddGdk
  album_name: ''
  collection_name: Omegle Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=1chrcjnRfi4
  album_name: ''
  collection_name: Guerrilla Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=IyYa-gTebrY
  album_name: ''
  collection_name: Stream of Consciousness
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=IyYa-gTebrY
  album_name: ''
  collection_name: Stream of Consciousness
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=ZbIcmL6cuZk
  album_name: ''
  collection_name: Stream of Consciousness
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=ZbIcmL6cuZk
  album_name: ''
  collection_name: Stream of Consciousness
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=iml3JBdmJyc
  album_name: ''
  collection_name: Stream of Consciousness
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=IULnhyDy4GQ
  album_name: ''
  collection_name: Stream of Consciousness
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=iP0z1X3hV7Q
  album_name: ''
  collection_name: Guerrilla Bars Clips
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=TVpDVtxI34w
  album_name: ''
  collection_name: Behind The Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=aIea7NWaJSY
  album_name: ''
  collection_name: Live Chat Clips
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=d5c6y4qe5Yc
  album_name: ''
  collection_name: Guerrilla Bars Unreleased
  video_title: ''
  ignore: false
  date_added: 2023-01-09
